name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodule init && git submodule update
      run: git submodule init && git submodule update
    - name: configure
      run: mkdir build && cd build && cmake .. -DFOREST_BUILD_TESTS=ON
    - name: build
      run: cmake --build build --config Debug
    - name: test
      run: cd build && ctest
