name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir build
      run: mkdir build
    - name: cd build
      run: cd build
    - name: cmake ..
      run: cmake ..
    - name: cpack -G DEB
      run: cpack -G DEB
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: build/*.deb
